{% set version = "2.1.4" %}

package:
  name: libgdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
  sha256: 79aa6331008af7c1d36d30e4a7dae92b2b8a3512a6084b672a2b2659731e6529
  patches:
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch
    # BUILT_AS_DYNAMIC_LIB
    - windowshdf5.patch
    # Use multiple cores on Windows
    - multiprocessor.patch

build:
  number: 9
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - curl >=7.44.0,<8
    - expat 2.2.*
    - freexl
    - geos 3.6.2
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.10.1
    - jpeg 9*
    - json-c  # [not win]
    - kealib 1.4.7
    - libdap4 3.18.*  # [not win]
    - libnetcdf 4.4.*
    - libpng >=1.6.32,<1.6.35
    - libspatialite
    - libtiff >=4.0.8,<4.0.10
    - openjpeg 2.3.*
    - poppler 0.61.*  # [not win]
    - postgresql
    - proj4 4.9.3
    - sqlite 3.20.*
    - xerces-c 3.2.0
    - zlib 1.2.11  # [not win]
    - geotiff
    - xz 5.2.*
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - curl >=7.44.1,<8
    - expat 2.2.*
    - freexl
    - geos 3.6.2
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.10.1
    - jpeg 9*
    - json-c  # [not win]
    - kealib 1.4.7
    - libdap4 3.18.*  # [not win]
    - libnetcdf 4.4.*
    - libpng >=1.6.32,<1.6.35
    - libpq
    - libspatialite
    - libtiff >=4.0.8,<4.0.10
    - openjpeg 2.3.*
    - poppler 0.61.*  # [not win]
    - proj4 4.9.3
    - sqlite 3.20.*
    - xerces-c 3.2.0
    - zlib 1.2.11  # [not win]
    - geotiff
    - xz 5.2.*
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - test_data
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
